/d435:
  camera:
    ros__parameters:
      serial_no: 819312071869 # d435
      base_frame_id: d435_link
      align_depth: true
      enable_pointcloud: true
      dense_pointcloud: true
      color0:
        enabled: true
        resolution: [640,480]
        fps: 30
      depth0:
        enabled: true
        resolution: [640,480]
        fps: 30
      infra1:
        enabled: true
        resolution: [640,480]
        fps: 30
      infra2:
        enabled: true
        resolution: [640,480]
        fps: 30